workers_dev = true
name = "rr-cf-sandbox1"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[env.preview]
name = "rr-cf-sandbox1-preview"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "rr-cf-sandbox1-production"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

