name = "rr-cf-sandbox1-local"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
workers_dev = true

[vars]
ENVIRONMENT = "local"
SERVICE_NAME = "rr-cf-sandbox1-local"

[[d1_databases]]
binding = "D1"
database_name = "d1-local"
database_id = "d1-local"
migrations_table = "d1_migrations"
migrations_dir = "migrations"

[env.preview]
name = "rr-cf-sandbox1-preview"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[env.preview.vars]
ENVIRONMENT = "preview"
SERVICE_NAME = "rr-cf-sandbox1-preview"

[[env.preview.d1_databases]]
binding = "D1"
database_name = "langapp-d1-preview"
database_id = "302b54d9-8b77-4668-8679-7b4b9bf63df2"
migrations_table = "d1_migrations"
migrations_dir = "migrations"

[env.production]
name = "rr-cf-sandbox1-production"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
ENVIRONMENT = "production"
SERVICE_NAME = "rr-cf-sandbox1-production"

[[env.production.d1_databases]]
binding = "D1"
database_name = "rr-cf-sandbox1-d1-production"
database_id = "862b0a54-3bb8-4175-9da3-0dd404504106"
migrations_table = "d1_migrations"
migrations_dir = "migrations"


