// Generated by Wrangler by running `wrangler types app//worker-configuration.d.ts --x-include-runtime`

interface Env {
	ENVIRONMENT: "local";
	SERVICE_NAME: "rr-cf-sandbox1-local";
	D1: D1Database;
}
